#!/usr/bin/env python

import sys
import os
import re
import numpy as np
import csv
import matplotlib.pyplot as plt

module_dir = os.environ["HOME"] + "/Programming/Python/Modules/"
sys.path.append(module_dir)

def empty_string(s):
	if s == '':
		return False
	
	return True

def read(filename, delim=','):
	filename_bin = re.sub("\.csv", ".bin", filename)
	
	f = open(filename_bin,'rb')
	if f:
		print "reading binary"
		
		return np.fromfile(filename_bin)
	else:
		print "no binary, reading text"
		
		with open( filename, 'rb' ) as f:
			reader = csv.reader( f, delimiter=delim, quoting=csv.QUOTE_NONNUMERIC, skipinitialspace=True )
			
			# skip first line
			
			
			rows=[]
	
			r = 0
			while 1:
				row = 0
				
				try:
					row = reader.next()
	
					#print row
	
					row = filter(empty_string, row)
	
					#print row
	
							#print row
					
					
					r += 1
				except ValueError:
					#print "ValueError"
					continue
				except NameError as err:
					print err
					sys.exit(0)
				except:
					print
					print row
					print sys.exc_info()[0]
					break
				
				rows.append( row )
	
	
	print len(rows)
	
	return np.array( rows )
	
	
