CPP_FILES = /home/chuck/git/python/test/pymake/test/src/main.cpp /home/chuck/git/python/test/pymake/test/src/foo.cpp
O_FILES   = /home/chuck/git/python/test/pymake/test/pymake_files/src/main.o /home/chuck/git/python/test/pymake/test/pymake_files/src/foo.o
/home/chuck/git/python/test/pymake/test/pymake_files/src/main.o:/home/chuck/git/python/test/pymake/test/src/main.cpp
	@echo /home/chuck/git/python/test/pymake/test/pymake_files/src
	@mkdir -p /home/chuck/git/python/test/pymake/test/pymake_files/src
	@g++ -std=c++0x /home/chuck/git/python/test/pymake/test/src/main.cpp -o /home/chuck/git/python/test/pymake/test/pymake_files/src/main.o
/home/chuck/git/python/test/pymake/test/pymake_files/src/foo.o:/home/chuck/git/python/test/pymake/test/src/foo.cpp
	@echo /home/chuck/git/python/test/pymake/test/pymake_files/src
	@mkdir -p /home/chuck/git/python/test/pymake/test/pymake_files/src
	@g++ -std=c++0x /home/chuck/git/python/test/pymake/test/src/foo.cpp -o /home/chuck/git/python/test/pymake/test/pymake_files/src/foo.o
clean:
	@rm -f /home/chuck/git/python/test/pymake/test/pymake_files/src/main.o /home/chuck/git/python/test/pymake/test/pymake_files/src/foo.o
